apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    {{- include "movies.labels" . | nindent 4 }}
    app.kubernetes.io/component: reverse-proxy
spec:
  replicas: {{ .Values.reverse-proxy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: reverse-proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reverse-proxy
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: reverse-proxy
          image: {{ .Values.reverse-proxy.image }}:{{ .Values.tag }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: http
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: http
